export var roster = {
  U2: {
    mortalLevelRank: 6,
    supremeKai: 'Pell',
    godOfDestruction: 'Heles',
    angel: 'Sour',
    warriors: [
      'Brianne de Chateau',
      'Hermila',
      'Jimeze',
      'Prum',
      'Rabanra',
      'Sanka Ku',
      'Su Roas',
      'Vikal',
      'Zarbuto',
      'Zirloin',
    ]
  },
  U3: {
    mortalLevelRank: 7,
    supremeKai: 'Ea',
    godOfDestruction: 'Mosco',
    angel: 'Campari',
    warriors: [
      'Biarra',
      'Borareta',
      'Katopesla',
      'Koitsukai',
      'Maji Kayo',
      'Narirama',
      'Nigrisshi',
      'Pancea',
      'Paparoni',
      'The Preecho',
    ],
  },
  U4: {
    mortalLevelRank: 9,
    supremeKai: 'Kuru',
    godOfDestruction: 'Quitela',
    angel: 'Cognac',
    warriors: [
      'Caway',
      'Damon',
      'Dercori',
      'Gamisaras',
      'Ganos',
      'Majora',
      'Monna',
      'Nink',
      'Shantza', 
      'Shosa',
    ],
  },
  U6: {
    mortalLevelRank: 10,
    supremeKai: 'Fuwa',
    godOfDestruction: 'Champa',
    angel: 'Vados',
    warriors: [
      'Auta Magetta',
      'Botamo',
      'Cabba',
      'Caulifla',
      'Dr. Rota',
      'Frost',
      'Hit',
      'Kale',
      'Pirina',
      'Saonel',
    ],
  },
  U7: {
    mortalLevelRank: 11,
    supremeKai: 'Shin',
    godOfDestruction: 'Beerus',
    angel: 'Whis',
    warriors: [
      'Android 17',
      'Android 18',
      'Frieza',
      'Gohan',
      'Goku',
      'Krillin',
      'Master Roshi',
      'Piccolo',
      'Tien Shinhan',
      'Vegeta',
    ],
  },
  U9: {
    mortalLevelRank: 12,
    supremeKai: 'Roh',
    godOfDestruction: 'Sidra',
    angel: 'Mojito',
    warriors: [
      'Basil',
      'Bergamo',
      'Chappil',
      'Comfrey', 
      'Hop',
      'Hyssop',
      'Lavender',
      'Oregano',
      'Roselle',
      'Sorrel',
    ],
  },
  U10: {
    mortalLevelRank: 8,
    supremeKai: 'Gowasu',
    godOfDestruction: 'Rumsshi',
    angel: 'Cus',
    warriors: [
      'Jilcol',
      'Jirasen',
      'Jium', 
      'Lilibeu',
      'Methiop',
      'Murichim',
      'Murisam',
      'Napapa',
      'Obuni',
      'Rubalt',
    ],
  },
  U11: {
    mortalLevelRank: 5,
    supremeKai: 'Khai',
    godOfDestruction: 'Belmod',
    angel: 'Marcarita',
    warriors: [
      'Cocotte',
      'Dyspo',
      'Jiren',
      'Kahseral',
      'Kettol',
      'Kunshi',
      'Toppo',
      'Tupper',
      'Vuon',
      'Zoiray',
    ],
  },
};
