export var roster = {
  U2: {
    mortalLevelRank: 6,
    supremeKai: 'Pell',
    godOfDestruction: 'Heles',
    angel: 'Sour',
    warriors: [
      'Brianne de Chateau',
      'Hermila',
      'Jimeze',
      'Prum',
      'Rabanra',
      'Sanka Ku',
      'Su Roas',
      'Vikal',
      'Zarbuto',
      'Zirloin',
    ]
  },
  U3: {
    mortalLevelRank: 7,
    supremeKai: 'Ea',
    godOfDestruction: 'Mosco',
    angel: 'Campari',
    warriors: [
      'Viara',
      'Bollarator',
      'Katopesla',
      'Koitsukai',
      'Maji Kayo',
      'Narirama',
      'Nigrisshi',
      'Panchia',
      'Paparoni',
      'The Preecho',
    ],
  },
  U4: {
    mortalLevelRank: 9,
    supremeKai: 'Kuru',
    godOfDestruction: 'Quitela',
    angel: 'Cognac',
    warriors: [
      'Caway',
      'Damon',
      'Dercori',
      'Gamisaras',
      'Ganos',
      'Majora',
      'Monna',
      'Nink',
      'Shantza', 
      'Shosa',
    ],
  },
  U6: {
    mortalLevelRank: 10,
    supremeKai: 'Fuwa',
    godOfDestruction: 'Champa',
    angel: 'Vados',
    warriors: [
      'Auta Magetta',
      'Botamo',
      'Cabba',
      'Caulifla',
      'Dr. Rota',
      'Frost',
      'Hit',
      'Kale',
      'Pirina',
      'Saonel',
    ],
  },
  U7: {
    mortalLevelRank: 11,
    supremeKai: 'Shin',
    godOfDestruction: 'Beerus',
    angel: 'Whis',
    warriors: [
      'Android 17',
      'Android 18',
      'Frieza',
      'Gohan',
      'Goku',
      'Krillin',
      'Master Roshi',
      'Piccolo',
      'Tien Shinhan',
      'Vegeta',
    ],
  },
  U9: {
    mortalLevelRank: 12,
    supremeKai: 'Roh',
    godOfDestruction: 'Sidra',
    angel: 'Mojito',
    warriors: [
      'Basil',
      'Bergamo',
      'Chappil',
      'Comfrey', 
      'Hop',
      'Hyssop',
      'Lavender',
      'Oregano',
      'Roselle',
      'Sorrel',
    ],
  },
  U10: {
    mortalLevelRank: 8,
    supremeKai: 'Gowasu',
    godOfDestruction: 'Rumsshi',
    angel: 'Cus',
    warriors: [
      'Jilcol',
      'Jirasen',
      'Jium', 
      'Lilibeu',
      'Methiop',
      'Murichim',
      'Murisam',
      'Napapa',
      'Obuni',
      'Rubalt',
    ],
  },
  U11: {
    mortalLevelRank: 5,
    supremeKai: 'Khai',
    godOfDestruction: 'Belmod',
    angel: 'Marcarita',
    warriors: [
      'Cocotte',
      'Dyspo',
      'Jiren',
      'Kahseral',
      'Kettol',
      'Kunshi',
      'Toppo',
      'Tupper',
      'Vuon',
      'Zoiray',
    ],
  },
};

export var eliminations = [
  { episode: 97, warrior: 'Lilibeu', by: ['Basil'] },
  { episode: 97, warrior: 'Nink', by: ['Goku'] },
  { episode: 98, warrior: 'Chappil', by: ['Goku'] },
  { episode: 98, warrior: 'Comfrey', by: ['Goku'] },
  { episode: 98, warrior: 'Hop', by: ['Vegeta'] },
  { episode: 98, warrior: 'Hyssop', by: ['Vegeta'] },
  { episode: 98, warrior: 'Oregano', by: ['Vegeta'] },
  { episode: 98, warrior: 'Sorrel', by: ['Android 18'] },
  { episode: 98, warrior: 'Roselle', by: ['Frieza', 'Roselle'] },
  { episode: 98, warrior: 'Basil', by: ['Goku', 'Vegeta'] },
  { episode: 98, warrior: 'Lavender', by: ['Goku', 'Vegeta'] },
  { episode: 98, warrior: 'Bergamo', by: ['Goku', 'Vegeta'] },
  { episode: 99, warrior: 'Jium', by: ['Krillin', 'Master Roshi'] },
  { episode: 99, warrior: 'Shosa', by: ['Android 18', 'Krillin'] },
  { episode: 99, warrior: 'Majora', by: ['Krillin'] },
  { episode: 99, warrior: 'Krillin', by: ['Frost'] },
  { episode: 100, warrior: 'Murisam', by: ['Cabba'] },
  { episode: 100, warrior: 'Nigrisshi', by: ['Cabba'] },
  { episode: 100, warrior: 'Narirama', by: ['Hit'] },
  { episode: 100, warrior: 'Napapa', by: ['Caulifla'] },
  { episode: 100, warrior: 'Methiop', by: ['Kale'] },
  { episode: 100, warrior: 'Vuon', by: ['Kale'] },
  { episode: 101, warrior: 'The Preecho', by: ['Master Roshi', 'Tien Shinhan'] },
  { episode: 101, warrior: 'Murichim', by: ['Frieza'] },
  { episode: 101, warrior: 'Tupper', by: ['Android 18'] },
  { episode: 101, warrior: 'Kahseral', by: ['Caulifla', 'Kale'] },
  { episode: 101, warrior: 'Kettol', by: ['Caulifla', 'Kale'] },
  { episode: 101, warrior: 'Zoiray', by: ['Caulifla', 'Kale'] },
  { episode: 101, warrior: 'Cocotte', by: ['Android 18'] },
  { episode: 102, warrior: 'Jirasen', by: ['Brianne de Chateau'] },
  { episode: 102, warrior: 'Vikal', by: ['Android 17'] },
  { episode: 102, warrior: 'Sanka Ku', by: ['Android 17'] },
  { episode: 103, warrior: 'Botamo', by: ['Gohan'] },
  { episode: 103, warrior: 'Jilcol', by: ['Jimeze'] },
  { episode: 103, warrior: 'Rubalt', by: ['Piccolo'] },
  { episode: 103, warrior: 'Obuni', by: ['Gohan'] },
  { episode: 104, warrior: 'Kunshi', by: ['Hit'] },
  { episode: 105, warrior: 'Caway', by: ['Caway', 'Master Roshi'] },
  { episode: 105, warrior: 'Dercori', by: ['Master Roshi'] },
  { episode: 105, warrior: 'Ganos', by: ['Master Roshi'] },
  { episode: 106, warrior: 'Hermila', by: ['Tien Shinhan'] },
  { episode: 106, warrior: 'Tien Shinhan', by: ['Hermila'] },
  { episode: 106, warrior: 'Prum', by: ['Vegeta'] },
  { episode: 106, warrior: 'Dr. Rota', by: ['Vegeta'] },
  { episode: 107, warrior: 'Maji Kayo', by: ['Jiren'] },
  { episode: 107, warrior: 'Auta Magetta', by: ['Vegeta'] },
  { episode: 107, warrior: 'Master Roshi', by: ['Frost', 'Master Roshi'] },
  { episode: 108, warrior: 'Jimeze', by: ['Frieza'] },
  { episode: 108, warrior: 'Frost', by: ['Frieza'] },
  { episode: 111, warrior: 'Hit', by: ['Jiren'] },
  { episode: 112, warrior: 'Monna', by: ['Cabba'] },
  { episode: 112, warrior: 'Cabba', by: ['Frieza'] },
  { episode: 116, warrior: 'Caulifla', by: ['Goku'] },
  { episode: 116, warrior: 'Kale', by: ['Goku'] },
  { episode: 117, warrior: 'Su Roas', by: ['Android 17'] },
  { episode: 117, warrior: 'Brianne de Chateau', by: ['Android 18'] },
  { episode: 118, warrior: 'Zirloin', by: ['Goku'] },
  { episode: 118, warrior: 'Zarbuto', by: ['Goku'] },
  { episode: 118, warrior: 'Rabanra', by: ['Goku'] },
  { episode: 118, warrior: 'Pirina', by: ['Gohan', 'Piccolo'] },
  { episode: 118, warrior: 'Saonel', by: ['Gohan', 'Piccolo'] },
  { episode: 119, warrior: 'Katopesla', by: ['Gamisaras'] },
  { episode: 119, warrior: 'Gamisaras', by: ['Piccolo'] },
  { episode: 119, warrior: 'Shantza', by: ['Piccolo'] },
  { episode: 119, warrior: 'Piccolo', by: ['Damon'] },
  { episode: 119, warrior: 'Damon', by: ['Android 17'] },
  { episode: 120, warrior: 'Viara', by: ['Android 18'] },
  { episode: 121, warrior: 'Android 18', by: ['Android 18', 'Bollarator', 'Koitsukai', 'Panchia', 'Paparoni'] },
  { episode: 121, warrior: 'Koitsukai', by: ['Android 17', 'Frieza', 'Gohan', 'Goku', 'Vegeta'] },
  { episode: 121, warrior: 'Panchia', by: ['Android 17', 'Frieza', 'Gohan', 'Goku', 'Vegeta'] },
  { episode: 121, warrior: 'Bollarator', by: ['Android 17', 'Frieza', 'Gohan', 'Goku', 'Vegeta'] },
  { episode: 121, warrior: 'Paparoni', by: ['Android 17', 'Frieza', 'Gohan', 'Goku', 'Vegeta'] },
  { episode: 124, warrior: 'Dyspo', by: ['Frieza', 'Gohan'] },
  { episode: 124, warrior: 'Gohan', by: ['Frieza', 'Gohan'] },
  { episode: 126, warrior: 'Toppo', by: ['Vegeta'] },
  { episode: 128, warrior: 'Vegeta', by: ['Jiren'] },
  { episode: 131, warrior: 'Frieza', by: ['Frieza'] },
  { episode: 131, warrior: 'Goku', by: ['Goku'] },
  { episode: 131, warrior: 'Jiren', by: ['Frieza', 'Goku'] },
];
